# Generated by Django 4.2 on 2023-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.URLField(default=1, verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
